services:
  - type: web
    name: face-frame
    env: python
    plan: free
    buildCommand: apt-get install -y libgles2 libgl1 libglib2.0-0 && pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
